# Generated by Django 3.2.5 on 2021-07-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0002_auto_20210727_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='about_title',
            field=models.CharField(default='About', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
