# Generated by Django 3.2.5 on 2021-07-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0003_auto_20210727_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='about_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
