# Generated by Django 3.2.5 on 2021-08-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0004_auto_20210727_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
