# Generated by Django 3.2.5 on 2021-08-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0005_alter_post_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='account_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='suite',
            field=models.CharField(default='', max_length=200),
        ),
    ]
