# Generated by Django 3.2.5 on 2021-08-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0006_auto_20210822_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='note',
            field=models.TextField(default='', max_length=500),
        ),
    ]
