# Generated by Django 3.2.5 on 2021-08-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0007_post_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
